**Credit:**
*This notebook contains an excerpt from the [Whirlwind Tour of Python](http://www.oreilly.com/programming/free/a-whirlwind-tour-of-python.csp) by Jake VanderPlas; the content is available [on GitHub](https://github.com/jakevdp/WhirlwindTourOfPython).*



**Presented by** : [Mohammad Abualhoul](https://www.linkedin.com/in/m-yakub/)




# The Basics of NumPy Arrays

Data manipulation in Python is nearly synonymous with NumPy array manipulation: even newer tools like Pandas ([Chapter 3](03.00-Introduction-to-Pandas.ipynb)) are built around the NumPy array.
This section will present several examples of using NumPy array manipulation to access data and subarrays, and to split, reshape, and join the arrays.
While the types of operations shown here may seem a bit dry and pedantic, they comprise the building blocks of many other examples used throughout the book.
Get to know them well!

We'll cover a few categories of basic array manipulations here:

- *Attributes of arrays*: Determining the size, shape, memory consumption, and data types of arrays
- *Indexing of arrays*: Getting and setting the value of individual array elements
- *Slicing of arrays*: Getting and setting smaller subarrays within a larger array
- *Reshaping of arrays*: Changing the shape of a given array
- *Joining and splitting of arrays*: Combining multiple arrays into one, and splitting one array into many

## NumPy Array Attributes

First let's discuss some useful array attributes.
We'll start by defining three random arrays, a one-dimensional, two-dimensional, and three-dimensional array.
We'll use NumPy's random number generator, which we will *seed* with a set value in order to ensure that the same random arrays are generated each time this code is run:

In [ ]:
import numpy as np

In [ ]:
L1=list(range(0,10))
L1

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
L2= np.array([L1])
L2

array([[1., 2., 3., 4.]])

In [ ]:
L3=[1,2,3,4,'Mohammad']

In [ ]:
np.array(L2)

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [ ]:
x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array

In [ ]:
x1

array([4, 4, 1, 3, 3, 1])

In [ ]:
x2

array([[0, 5, 9, 7],
       [4, 3, 0, 5],
       [7, 4, 7, 4]])

Each array has attributes ``ndim`` (the number of dimensions), ``shape`` (the size of each dimension), and ``size`` (the total size of the array):

In [ ]:
x3

In [ ]:
len(x1)

6

In [ ]:
len(x3)

3

In [ ]:
x3.ndim

3

In [ ]:
x3.shape

(3, 4, 5)

In [ ]:
list1=[[0,1,2],[0,3,4]]
list1

[[0, 1, 2], [0, 3, 4]]

In [ ]:
type(list1)

list

In [ ]:
type(x3)

numpy.ndarray

In [ ]:
type(x3[0][0][0])

numpy.int64

**int and Floats**

In [ ]:
L1 = [1,2,3,4]
L2 = [5,6,7,12]

In [ ]:
Integers = np.array([L1,L2])
Integers

array([[ 1,  2,  3,  4],
       [ 5,  6,  7, 12]])

In [ ]:
L1 = [1.,2,3,4]

In [ ]:
Floats = np.array([L1,L2])
Floats

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7., 12.]])

In [ ]:
x2

array([[0, 5, 9, 7],
       [4, 3, 0, 5],
       [7, 4, 7, 4]])

In [ ]:
x2.size

12

In [ ]:
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60


In [ ]:
x3

array([[[1, 0, 6, 4, 6],
        [7, 8, 4, 4, 9],
        [5, 2, 2, 8, 8],
        [0, 9, 0, 9, 8]],

       [[2, 6, 0, 6, 7],
        [7, 0, 5, 8, 1],
        [7, 6, 1, 2, 8],
        [3, 9, 1, 2, 6]],

       [[4, 5, 5, 7, 1],
        [6, 7, 5, 8, 9],
        [4, 5, 9, 0, 6],
        [4, 2, 2, 6, 0]]])

In [ ]:
x3.sort()
x3

array([[[0, 1, 4, 6, 6],
        [4, 4, 7, 8, 9],
        [2, 2, 5, 8, 8],
        [0, 0, 8, 9, 9]],

       [[0, 2, 6, 6, 7],
        [0, 1, 5, 7, 8],
        [1, 2, 6, 7, 8],
        [1, 2, 3, 6, 9]],

       [[1, 4, 5, 5, 7],
        [5, 6, 7, 8, 9],
        [0, 4, 5, 6, 9],
        [0, 2, 2, 4, 6]]])

Another useful attribute is the ``dtype``, the data type of the array (which we discussed previously in [Understanding Data Types in Python](02.01-Understanding-Data-Types.ipynb)):

In [ ]:
print("dtype:", x3.dtype)

dtype: int64


In [ ]:
x3.dtype

dtype('int64')

In [ ]:
darr=np.array(['Rawan','Hala','Osama','Khader'])
darr

array(['Rawan', 'Hala', 'Osama', 'Khader'], dtype='<U6')

In [ ]:
darr.dtype

dtype('<U6')

In [ ]:
L1

[1.0, 2, 3, 4]

In [ ]:
 w = np.array((L1,L2), dtype=np.str)
 w

array([['1.0', '2', '3', '4'],
       ['5', '6', '7', '12']], dtype='<U3')

In [ ]:
 w = np.ones((10,10), dtype=np.int64)
 w

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

Other attributes include ``itemsize``, which lists the size (in bytes) of each array element, and ``nbytes``, which lists the total size (in bytes) of the array:

In [ ]:
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

itemsize: 8 bytes
nbytes: 480 bytes


In [ ]:
x3.size*x3.itemsize

480

In general, we expect that ``nbytes`` is equal to ``itemsize`` times ``size``.

## Array Indexing: Accessing Single Elements

If you are familiar with Python's standard list indexing, indexing in NumPy will feel quite familiar.
In a one-dimensional array, the $i^{th}$ value (counting from zero) can be accessed by specifying the desired index in square brackets, just as with Python lists:

In [ ]:
x1

array([4, 4, 1, 3, 3, 1])

In [ ]:
x1[0]

9

In [ ]:
x1[4]

3

To index from the end of the array, you can use negative indices:

In [ ]:
x1[-1]

1

In [ ]:
x1[-2]

3

In a multi-dimensional array, items can be accessed using a comma-separated tuple of indices:

In [ ]:
x2.shape

(3, 4)

In [ ]:
x2.shape

(3, 4)

In [ ]:
list1[0][1]

1

In [ ]:
x2[1, -1]

6

In [ ]:
x2[1,3]

6

In [ ]:
x2[0, 0]

7

In [ ]:
x2[2, 0]

1

In [ ]:
x2[2, -1]

3

Values can also be modified using any of the above index notation:

In [ ]:
x2[0][0] = 12
x2

array([[12,  3,  3,  5],
       [ 9,  5,  3,  6],
       [ 1,  1,  9,  3]])

In [ ]:
x2[1,1]=2.9
x2

array([[12,  3,  3,  5],
       [ 9,  2,  3,  6],
       [ 1,  1,  9,  3]])

In [ ]:
x2=x2.astype(str)

In [ ]:

x2[1,1]='string'
x2

array([['12', '3', '3', '5'],
       ['9', 'string', '3', '6'],
       ['1', '1', '9', '3']], dtype='<U21')

In [ ]:
x2.dtype

dtype('<U21')

Keep in mind that, unlike Python lists, NumPy arrays have a fixed type.
This means, for example, that if you attempt to insert a floating-point value to an integer array, the value will be silently truncated. Don't be caught unaware by this behavior!


# <p><img alt="Colaboratory logo" height="30px" src="/img/colab_favicon.ico" align="left" hspace="10px" vspace="0px"></p>

**Hands-on:** 
- Generate numpy array with size =(5,6)
- Once generated, change last element in your 5x6 array with the value Myarray[-1]=20.99

In [ ]:
import numpy as np
# Your code

## Array Slicing: Accessing Subarrays

Just as we can use square brackets to access individual array elements, we can also use them to access subarrays with the *slice* notation, marked by the colon (``:``) character.
The NumPy slicing syntax follows that of the standard Python list; to access a slice of an array ``x``, use this:
``` python
x[start:stop:step]
```
If any of these are unspecified, they default to the values ``start=0``, ``stop=``*``size of dimension``*, ``step=1``.
We'll take a look at accessing sub-arrays in one dimension and in multiple dimensions.

### One-dimensional subarrays

In [ ]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
x[:5]  # first five elements ... Simple List

array([0, 1, 2, 3, 4])

In [ ]:
x[5:]  # elements after index 5  Simple List

array([5, 6, 7, 8, 9])

In [ ]:
x[4:7]  # middle sub-array

array([4, 5, 6])

In [ ]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
x[::2]  # every other element with 2 steps

array([0, 2, 4, 6, 8])

In [ ]:
x[1::2]  # every other element, starting at index 1

array([1, 3, 5, 7, 9])

In [ ]:
x[1::5]  # every other element, starting at index 1

array([1, 6])

A potentially confusing case is when the ``step`` value is negative.
In this case, the defaults for ``start`` and ``stop`` are swapped.
This becomes a convenient way to reverse an array:

In [ ]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
x[::-1]  # all elements, reversed ... every other element reverse

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [ ]:
x[::-2]  # all elements, reversed with 2 steps

array([9, 7, 5, 3, 1])

In [ ]:
x[5:9:-2]  # reversed every other from index 5

array([], dtype=int64)

In [ ]:
x[5:9:2]  # reversed every other from index 5

array([5, 7])

In [ ]:
x[-5:-9:-2]  # reversed every other from index 5

array([5, 3])

### Multi-dimensional subarrays

Multi-dimensional slices work in the same way, with multiple slices separated by commas.
For example:

In [ ]:
x1

array([9, 6, 1, 1, 3, 4])

In [ ]:
x1[0:5:2]

array([9, 1, 3])

In [ ]:
x2

array([['12', '3', '3', '5'],
       ['9', 'string', '3', '6'],
       ['1', '1', '9', '3']], dtype='<U21')

In [ ]:
x2[:2, :3]  # two rows, three columns

array([['12', '3', '3'],
       ['9', 'string', '3']], dtype='<U21')

In [ ]:
x2[:3, :2]  # all rows, every other column

array([['12', '3'],
       ['9', 'string'],
       ['1', '1']], dtype='<U21')

In [ ]:
x2

array([['12', '3', '3', '5'],
       ['9', 'string', '3', '6'],
       ['1', '1', '9', '3']], dtype='<U21')

In [ ]:
x2[::, ::3]  # all rows, every other column

array([['12', '5'],
       ['9', '6'],
       ['1', '3']], dtype='<U21')

Finally, subarray dimensions can even be reversed together:

In [ ]:
x2

array([['12', '3', '3', '5'],
       ['9', 'string', '3', '6'],
       ['1', '1', '9', '3']], dtype='<U21')

In [ ]:
x2[::-1, ::1]

array([['1', '1', '9', '3'],
       ['9', 'string', '3', '6'],
       ['12', '3', '3', '5']], dtype='<U21')

In [ ]:
x2[::-1, ::2]

array([['1', '9'],
       ['9', '3'],
       ['12', '3']], dtype='<U21')


# <p><img alt="Colaboratory logo" height="30px" src="/img/colab_favicon.ico" align="left" hspace="10px" vspace="0px"></p>

**Hands-on:**

In [ ]:
np.arange(1,26)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [ ]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])


* WRITE CODE HERE THAT REPRODUCES THE OUTPUTs OF THE CELLs BELOW


```
array([[ 1,  3,  5],
       [11, 13, 15]])


array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11],
       [20, 19, 18, 17, 16]])
```




In [ ]:
mat[0:3:2,::2]

array([[ 1,  3,  5],
       [11, 13, 15]])

In [ ]:
mat[:4,::-1]

array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11],
       [20, 19, 18, 17, 16]])

array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11],
       [20, 19, 18, 17, 16]])

#### Accessing array rows and columns

One commonly needed routine is accessing of single rows or columns of an array.
This can be done by combining indexing and slicing, using an empty slice marked by a single colon (``:``):

In [ ]:
x2

array([['12', '3', '3', '5'],
       ['9', 'string', '3', '6'],
       ['1', '1', '9', '3']], dtype='<U21')

In [ ]:
print(x2[:, 2])  # first column of x2

['3' '3' '9']


In [ ]:
arr4=x2[:, 2]
arr4

array(['3', '3', '9'], dtype='<U21')

In [ ]:
print(x2[0, :])  # first row of x2

['12' '3' '3' '5']


In the case of row access, the empty slice can be omitted for a more compact syntax:

In [ ]:
print(x2[0])  # equivalent to x2[0, :]

['12' '3' '3' '5']


### Subarrays as no-copy views

One important–and extremely useful–thing to know about array slices is that they return *views* rather than *copies* of the array data.
This is one area in which NumPy array slicing differs from Python list slicing: in lists, slices will be copies.
Consider our two-dimensional array from before:

In [ ]:
print(x2)

[['12' '3' '3' '5']
 ['9' 'string' '3' '6']
 ['1' '1' '9' '3']]


Let's extract a $2 \times 2$ subarray from this:

In [ ]:
x2_sub = x2[:2, :2]
print(x2_sub)

[['12' '3']
 ['9' 'string']]


Now if we modify this subarray, we'll see that the original array is changed! Observe:

In [ ]:
x2_sub[0, 0] = 99
print(x2_sub)

[['99' '3']
 ['9' 'string']]


In [ ]:
x2

array([['99', '3', '3', '5'],
       ['9', 'string', '3', '6'],
       ['1', '1', '9', '3']], dtype='<U21')

This default behavior is actually quite useful: it means that when we work with large datasets, we can access and process pieces of these datasets without the need to copy the underlying data buffer.

### Creating copies of arrays

Despite the nice features of array views, it is sometimes useful to instead explicitly copy the data within an array or a subarray. This can be most easily done with the ``copy()`` method:

In [ ]:
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)

[['99' '3']
 ['9' 'string']]


If we now modify this subarray, the original array is not touched:

In [ ]:
x2_sub_copy[0, 0] = 42
print(x2_sub_copy)

[['42' '3']
 ['9' 'string']]


In [ ]:
print(x2)

[['99' '3' '3' '5']
 ['9' 'string' '3' '6']
 ['1' '1' '9' '3']]


# <p><img alt="Colaboratory logo" height="30px" src="/img/colab_favicon.ico" align="left" hspace="10px" vspace="0px"></p>

**Hands-on:**



* WRITE CODE HERE THAT REPRODUCES THE OUTPUTs OF THE CELLs BELOW


```
array([[ 2],
       [ 7],
       [12]])

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])
```



In [ ]:
# Your code goes here!

- copy

* Put the second subarray in a variable and multiply it by 3 without modifying the original mat array

In [ ]:
# your code goes here!

## Reshaping of Arrays

Another useful type of operation is reshaping of arrays.
The most flexible way of doing this is with the ``reshape`` method.
For example, if you want to put the numbers 1 through 9 in a $3 \times 3$ grid, you can do the following:

In [ ]:
np.arange(1, 9)

In [ ]:
grid = np.arange(1, 10).reshape((3, 3))
print(grid)

Note that for this to work, the size of the initial array must match the size of the reshaped array. 
Where possible, the ``reshape`` method will use a no-copy view of the initial array, but with non-contiguous memory buffers this is not always the case.

Another common reshaping pattern is the conversion of a one-dimensional array into a two-dimensional row or column matrix.
This can be done with the ``reshape`` method, or more easily done by making use of the ``newaxis`` keyword within a slice operation:

In [ ]:
x = np.array([1, 2, 3])

# row vector via reshape
x.reshape((1, 3))

array([[1, 2, 3]])

In [ ]:
# row vector via newaxis
x[np.newaxis, :]

In [ ]:
x = np.array([1, 2, 3])
x

In [ ]:
x.shape

(3,)

In [ ]:
# column vector via reshape
x.reshape((3, 1))

In [ ]:
x

In [ ]:
# column vector via newaxis
x[:, np.newaxis]

We will see this type of transformation often throughout the remainder of the book.

# <p><img alt="Colaboratory logo" height="30px" src="/img/colab_favicon.ico" align="left" hspace="10px" vspace="0px"></p>

**Hands-on:**



* WRITE CODE HERE THAT REPRODUCES THE OUTPUTs OF THE CELLs BELOW

```
array([[ 0.01,  0.02,  0.03,  0.04,  0.05,  0.06,  0.07,  0.08,  0.09,  0.1 ],
       [ 0.11,  0.12,  0.13,  0.14,  0.15,  0.16,  0.17,  0.18,  0.19,  0.2 ],
       [ 0.21,  0.22,  0.23,  0.24,  0.25,  0.26,  0.27,  0.28,  0.29,  0.3 ],
       [ 0.31,  0.32,  0.33,  0.34,  0.35,  0.36,  0.37,  0.38,  0.39,  0.4 ],
       [ 0.41,  0.42,  0.43,  0.44,  0.45,  0.46,  0.47,  0.48,  0.49,  0.5 ],
       [ 0.51,  0.52,  0.53,  0.54,  0.55,  0.56,  0.57,  0.58,  0.59,  0.6 ],
       [ 0.61,  0.62,  0.63,  0.64,  0.65,  0.66,  0.67,  0.68,  0.69,  0.7 ],
       [ 0.71,  0.72,  0.73,  0.74,  0.75,  0.76,  0.77,  0.78,  0.79,  0.8 ],
       [ 0.81,  0.82,  0.83,  0.84,  0.85,  0.86,  0.87,  0.88,  0.89,  0.9 ],
       [ 0.91,  0.92,  0.93,  0.94,  0.95,  0.96,  0.97,  0.98,  0.99,  1.  ]])
       



* Add a third access to the output array

## Array Concatenation and Splitting

All of the preceding routines worked on single arrays. It's also possible to combine multiple arrays into one, and to conversely split a single array into multiple arrays. We'll take a look at those operations here.

### Concatenation of arrays

Concatenation, or joining of two arrays in NumPy, is primarily accomplished using the routines ``np.concatenate``, ``np.vstack``, and ``np.hstack``.
``np.concatenate`` takes a tuple or list of arrays as its first argument, as we can see here:

In [ ]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([y, x])

array([3, 2, 1, 1, 2, 3])

In [ ]:
np.union1d(x,y)

array([1, 2, 3])

You can also concatenate more than two arrays at once:

In [ ]:
z = [99, 99, 99]
print(np.concatenate([x, y, z]))

[ 1  2  3  3  2  1 99 99 99]


It can also be used for two-dimensional arrays:

In [ ]:
grid = np.array([[1, 2, 3],
                 [4, 5, 6]])
grid

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# concatenate along the first axis
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [ ]:
print(grid)
print(grid)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]


In [ ]:
# concatenate along the second axis (zero-indexed)
np.concatenate([grid, grid], axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [ ]:
# concatenate along the second axis (zero-indexed)
np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

For working with arrays of mixed dimensions, it can be clearer to use the ``np.vstack`` (vertical stack) and ``np.hstack`` (horizontal stack) functions:

In [ ]:
grid = np.array([[1, 2, 3],
                 [4, 5, 6]])

grid

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
grid2 = np.array([[9, 8],
                 [6, 5]])

In [ ]:
np.stack([grid,grid])

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [ ]:
np.concatenate([grid,grid])

In [ ]:
grid

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
grid2

array([[9, 8],
       [6, 5]])

In [ ]:
np.hstack([grid,grid2])

array([[1, 2, 3, 9, 8],
       [4, 5, 6, 6, 5]])

In [ ]:
np.vstack([grid.T,grid2])

array([[1, 4],
       [2, 5],
       [3, 6],
       [9, 8],
       [6, 5]])

In [ ]:
np.vstack([grid.T,grid2])

In [ ]:
x1=[1,2,3,4]
x2=[5,6,7,8]

In [1]:
np.vstack([x1,x2])

NameError: ignored

In [ ]:
x

array([1, 2, 3])

In [ ]:
y = np.array([[99],
              [99],
              [99],
              [99]])

y

array([[99],
       [99],
       [99],
       [99]])

In [ ]:
y.shape

(3, 1)

In [ ]:
grid.nbytes

48

In [ ]:
grid.data.nbytes

48

Similary, ``np.dstack`` will stack arrays along the third axis.

### Splitting of arrays

The opposite of concatenation is splitting, which is implemented by the functions ``np.split``, ``np.hsplit``, and ``np.vsplit``.  For each of these, we can pass a list of indices giving the split points:

In [ ]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
np.split(x, 3)

In [ ]:
x =np.array([x])
np.split(x, 2)

In [ ]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
xx = [55, 66, 77, 88, 99, 99,99, 99]

In [ ]:
a,b,c=np.array_split(x,3)

In [ ]:
a

array([1, 2, 3])

In [ ]:
np.split(x, 1)

In [ ]:
np.split()

In [ ]:
myarr=np.array([np.arange(4,10), np.arange(4,10)+5])
myarr

array([[ 4,  5,  6,  7,  8,  9],
       [ 9, 10, 11, 12, 13, 14]])

In [ ]:
np.split(myarr,1)

[array([[ 4,  5,  6,  7,  8,  9],
        [ 9, 10, 11, 12, 13, 14]])]

In [ ]:
np.split(myarr,4)

ValueError: ignored

In [ ]:
x1, x2, x3, x4= np.split(x, [3,5,6])
print(x1, x2, x3,x4)

[1 2 3] [99 99] [3] [2 1]


Notice that *N* split-points, leads to *N + 1* subarrays.
The related functions ``np.hsplit`` and ``np.vsplit`` are similar:

In [ ]:
 np.split(x, [3,5])

[array([[[ 1,  2,  3, 99, 99,  3,  2,  1]]]),
 array([], shape=(0, 1, 8), dtype=int64),
 array([], shape=(0, 1, 8), dtype=int64)]

In [ ]:
 np.split(x, [3,5,6])

[array([[[ 1,  2,  3, 99, 99,  3,  2,  1]]]),
 array([], shape=(0, 1, 8), dtype=int64),
 array([], shape=(0, 1, 8), dtype=int64),
 array([], shape=(0, 1, 8), dtype=int64)]

In [ ]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [ ]:
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
left, mid, right = np.hsplit(grid, [2,3])
print(left)


[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]


In [ ]:
mid

array([[ 2],
       [ 6],
       [10],
       [14]])

In [ ]:
print(right)

[[ 3]
 [ 7]
 [11]
 [15]]


Similarly, ``np.dsplit`` will split arrays along the third axis.

### <p><img alt="Colaboratory logo" height="30px" src="/img/colab_favicon.ico" align="left" hspace="10px" vspace="0px"></p>**`Hands-on`**


In [ ]:
arr=np.arange(1,19)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18])

In [ ]:
np.arange(1,19).reshape(6,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [ ]:
np.vsplit(np.arange(1,19).reshape(6,3),3)


[array([[1, 2, 3],
        [4, 5, 6]]), array([[ 7,  8,  9],
        [10, 11, 12]]), array([[13, 14, 15],
        [16, 17, 18]])]

* Convert arr to the following form:
```
[array([[1, 2, 3]]),
 array([[4, 5, 6]]),
 array([[7, 8, 9]]),
 array([[10, 11, 12]]),
 array([[13, 14, 15]]),
 array([[16, 17, 18]])]
