**Credit:**
*This notebook contains an excerpt from the [Whirlwind Tour of Python](http://www.oreilly.com/programming/free/a-whirlwind-tour-of-python.csp) by Jake VanderPlas; the content is available [on GitHub](https://github.com/jakevdp/WhirlwindTourOfPython).*



**Presented by** : [Mohammad Abualhoul](https://www.linkedin.com/in/m-yakub/) 

# List Comprehensions

If you read enough Python code, you'll eventually come across the terse and efficient construction known as a *list comprehension*.
This is one feature of Python I expect you will fall in love with if you've not used it before; it looks something like this:

In [ ]:
[i+1 for i in range(20) if i % 3 > 0]

[2, 3, 5, 6, 8, 9, 11, 12, 14, 15, 17, 18, 20]

The result of this is a list of numbers which excludes multiples of 3.
While this example may seem a bit confusing at first, as familiarity with Python grows, reading and writing list comprehensions will become second nature.

In [ ]:
[i*2 for i in range(20) if  i % 2==0]

[0, 4, 8, 12, 16, 20, 24, 28, 32, 36]

In [ ]:
%%timeit
txns = [1.09, 23.56, 57.84, 4.56, 6.78]
TAX_RATE = .08
final_prices=[]
def get_price_with_tax(txn):
  return txn * (1 + TAX_RATE)
for i in txns:
  final_prices.append(get_price_with_tax(i))
# print (i,txns.index(i))
final_prices

1000000 loops, best of 5: 1.29 µs per loop


In [ ]:
%%timeit
txns = [1.09, 23.56, 57.84, 4.56, 6.78]
TAX_RATE = .08
def get_price_with_tax(txn):
  return txn * (1 + TAX_RATE)
final_prices = [get_price_with_tax(i) for i in txns]
final_prices

1000000 loops, best of 5: 1.3 µs per loop


In [ ]:
%%timeit
txns = [1.09, 23.56, 57.84, 4.56, 6.78]
TAX_RATE = .08
#def get_price_with_tax(txn):
#  return txn * (1 + TAX_RATE)
get_price_with_tax = lambda txn : txn * (1 + TAX_RATE)
final_prices = [get_price_with_tax(i) for i in txns]
final_prices

The slowest run took 4.36 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 5: 1.16 µs per loop


## Basic List Comprehensions
List comprehensions are simply a way to compress a list-building for-loop into a single short, readable line.
For example, here is a loop that constructs a list of the first 12 square integers:

In [ ]:
%time
L = []
for n in range(10000):
    L.append(n ** 2)

CPU times: user 4 µs, sys: 0 ns, total: 4 µs
Wall time: 8.82 µs


The list comprehension equivalent of this is the following:

In [ ]:
%time
L=[n ** 2 for n in range(10000)]

CPU times: user 2 µs, sys: 0 ns, total: 2 µs
Wall time: 5.72 µs


As with many Python statements, you can almost read-off the meaning of this statement in plain English: "construct a list consisting of the square of ``n`` for each ``n`` up to 12".

This basic syntax, then, is ``[``*``expr``* ``for`` *``var``* ``in`` *``iterable``*``]``, where *``expr``* is any valid expression, *``var``* is a variable name, and *``iterable``* is any iterable Python object.

-----------------

1.   List item
2.   List item


<p><img alt="Colaboratory logo" height="30px" src="/img/colab_favicon.ico" align="left" hspace="10px" vspace="0px"></p>


**Hands-on:**
  - Use comprehensive list to create $\frac{1}{x}$ for `x =[5,6,7,8, ....,20]`. The output should be :

```
[0.2,
 0.16666666666666666,
 0.14285714285714285,
 0.125,
 0.1111111111111111,
 0.1,
 0.09090909090909091,
 0.08333333333333333,
 0.07692307692307693,
 0.07142857142857142,
 0.06666666666666667,
 0.0625,
 0.058823529411764705,
 0.05555555555555555,
 0.05263157894736842,
 0.05]
```

---------

In [ ]:
[1/i for i in range(5,20)]

[0.2,
 0.16666666666666666,
 0.14285714285714285,
 0.125,
 0.1111111111111111,
 0.1,
 0.09090909090909091,
 0.08333333333333333,
 0.07692307692307693,
 0.07142857142857142,
 0.06666666666666667,
 0.0625,
 0.058823529411764705,
 0.05555555555555555,
 0.05263157894736842]

## Multiple Iteration
Sometimes you want to build a list not just from one value, but from two. To do this, simply add another ``for`` expression in the comprehension:

In [ ]:
print(*range(7))

0 1 2 3 4 5 6


In [ ]:
x=list()
for i in range(2):
  for j in range(3):
     x.append((i,j))

x

[(0, 0), (0, 1), (0, 2), (1, 0), (1, 1), (1, 2)]

In [ ]:
[i for i in range(2)]

[0, 1]

In [ ]:
[(i) for i in range(2)]

[0, 1]

In [ ]:
[(i, j) for i in range(2) for j in range(3)]

[(0, 0), (0, 1), (0, 2), (1, 0), (1, 1), (1, 2)]

In [ ]:
[(i, j, k) for i in range(2) for j in range(3) for k in range(5)]

In [ ]:
[x for b in range(2) for x in range(3)]

[0, 1, 2, 0, 1, 2]

In [ ]:
[(x,b) for b in range(2) for x in range(3)]

[(0, 0), (1, 0), (2, 0), (0, 1), (1, 1), (2, 1)]

Notice that the second ``for`` expression acts as the interior index, varying the fastest in the resulting list.
This type of construction can be extended to three, four, or more iterators within the comprehension, though at some point code readibility will suffer!

## Conditionals on the Iterator
You can further control the iteration by adding a conditional to the end of the expression.
In the first example of the section, we iterated over all numbers from 1 to 20, but left-out multiples of 3.
Look at this again, and notice the construction:

In [ ]:
[val for val in range(20) if val % 3 > 0]

[1, 2, 4, 5, 7, 8, 10, 11, 13, 14, 16, 17, 19]

The expression ``(i % 3 > 0)`` evaluates to ``True`` unless ``val`` is divisible by 3.
Again, the English language meaning can be immediately read off: "Construct a list of values for each value up to 20, but only if the value is not divisible by 3".
Once you are comfortable with it, this is much easier to write – and to understand at a glance – than the equivalent loop syntax:

In [ ]:
L = []
for val in range(20):
    if val % 3:
        L.append(val)
L

In [ ]:
[(a,1/i) for a in range(15) for i in range(5,20)]

In [ ]:
[(a,1/i) for a in range(15) for i in range(5,20)]

In [ ]:
x=list()
for i in range(15):
  for j in range(5,20):
    if i%15==0:
      x.append((i,j))

x

In [ ]:
a=[range(15)]
print(*range(15))

0 1 2 3 4 5 6 7 8 9 10 11 12 13 14


In [ ]:
[(a,1/i) for a in range(0,15,1) if a%5 > 1 for i in range(5,20)]

## Conditionals on the Value

Python has ``lambda`` functions where a simple expression is desired:

In [ ]:
val = -10
val if val >= 0 else -val

We see that this simply duplicates the functionality of the built-in ``abs()`` function, but the construction lets you do some really interesting things within list comprehensions.
This is getting pretty complicated now, but you could do something like this:

In [ ]:
list(range(-4,5))

[-4, -3, -2, -1, 0, 1, 2, 3, 4]

In [ ]:
[val if val % 2 else -val 
 for val in range(0,20) if val % 3]

[1, -2, -4, 5, 7, -8, -10, 11, 13, -14, -16, 17, 19]

In [ ]:
[1, 2, 4, 5, 7, 8, 10, 11, 13, 14, 16, 17, 19]

Note the line break within the list comprehension before the ``for`` expression: this is valid in Python, and is often a nice way to break-up long list comprehensions for greater readibility.
Look this over: what we're doing is constructing a list, leaving out multiples of 3, and negating all mutliples of 2.

Once you understand the dynamics of list comprehensions, it's straightforward to move on to other types of comprehensions. The syntax is largely the same; the only difference is the type of bracket you use.

For example, with curly braces you can create a ``set`` with a *set comprehension*:

In [ ]:
{n**2 for n in range(12)}

{0, 1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121}

Recall that a ``set`` is a collection that contains no duplicates.
The set comprehension respects this rule, and eliminates any duplicate entries:

In [ ]:
{a % 3 for a in range(1000)}

{0, 1, 2}

In [ ]:
{(a,b) for a in range(20,30) for b in range(10)}

With a slight tweak, you can add a colon (``:``) to create a *dict comprehension*:

In [ ]:
{n:n**2 for n in range(6)}

{0: 0, 1: 1, 2: 4, 3: 9, 4: 16, 5: 25}

Finally, if you use parentheses rather than square brackets, you get what's called a *generator expression*:

In [ ]:
(n**2 for n in range(12))

0 1 4 9 16 25 36 49 64 81 100 121


In [ ]:
print(*(n**2 for n in range(12)))

0 1 4 9 16 25 36 49 64 81 100 121


A generator expression is essentially a list comprehension in which elements are generated as-needed rather than all at-once, and the simplicity here belies the power of this language feature: we'll explore this more next.

In [ ]:
for sqn in (n**2 for n in range(100000000)):
  if sqn > 100:
    break;
  else:
    print(sqn)

-----------------
<p><img alt="Colaboratory logo" height="30px" src="/img/colab_favicon.ico" align="left" hspace="10px" vspace="0px"></p>


**Hands-on:**
  - Use comprehensive dictionary to create `{x:` $\frac{1}{x}$ `}` dictionary  for `x =[100,101,102,103, ....,110]`. The output should be :



```

{100: 0.01,
 101: 0.009900990099009901,
 102: 0.00980392156862745,
 103: 0.009708737864077669,
 104: 0.009615384615384616,
 105: 0.009523809523809525,
 106: 0.009433962264150943,
 107: 0.009345794392523364,
 108: 0.009259259259259259,
 109: 0.009174311926605505,
 110: 0.00909090909090909}
```



---------

-----------------
<p><img alt="Colaboratory logo" height="30px" src="/img/colab_favicon.ico" align="left" hspace="10px" vspace="0px"></p>


**Hands-on:**
  - How about we use List comprehension to generate transpose array!

  You have matrix, generate the given output.




---------

In [4]:
import numpy as np

In [1]:
# %%timeit
matrix = [[1, 2], [3,4], [5,6], [7,8]]
transpose = [[x[i] for x in matrix] for i in range(2)]

[[1, 3, 5, 7], [2, 4, 6, 8]]


In [6]:
transpose

[[1, 3, 5, 7], [2, 4, 6, 8]]

In [7]:
matrix

[[1, 2], [3, 4], [5, 6], [7, 8]]

In [8]:
np.array(matrix)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [9]:
np.array(transpose)

array([[1, 3, 5, 7],
       [2, 4, 6, 8]])

In [5]:
matrix2 =np.array(matrix)
matrix2

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [14]:
# %%timeit
matrix2.transpose()

array([[1, 3, 5, 7],
       [2, 4, 6, 8]])

In [13]:
# %%timeit
matrix2.T

array([[1, 3, 5, 7],
       [2, 4, 6, 8]])

In [ ]:
np.transpose(np.array(matrix))

array([[1, 3, 5, 7],
       [2, 4, 6, 8]])

In [ ]:
np.T(matrix)

In [ ]:
np.transpose(matrix)

array([[1, 3, 5, 7],
       [2, 4, 6, 8]])

In [17]:
np.sum(matrix)

36

In [ ]:
matrix.s

In [18]:
matrix2.sum()

36