# Importing Libraries

In [57]:
import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# Importing the dataset

In [58]:
df0 = pd.read_csv('Data.csv')
df0

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [59]:
# Separate dependent from independent variables
X = df0.iloc[:,:-1].values
y = df0.iloc[:,-1].values

# Dealing with missing data

In [60]:
imputer = SimpleImputer(missing_values = np.nan, strategy = 'mean')
imputer.fit(X[:,1:3])
X[:,1:3] = imputer.transform(X[:,1:3])
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

# Encoding Categorical Data

## Encoding Independent Variables

In [61]:
ct = ColumnTransformer(transformers= [('encoder',OneHotEncoder(),[0])], remainder= 'passthrough')
X = ct.fit_transform(X)
X

array([[1.0, 0.0, 0.0, 44.0, 72000.0],
       [0.0, 0.0, 1.0, 27.0, 48000.0],
       [0.0, 1.0, 0.0, 30.0, 54000.0],
       [0.0, 0.0, 1.0, 38.0, 61000.0],
       [0.0, 1.0, 0.0, 40.0, 63777.77777777778],
       [1.0, 0.0, 0.0, 35.0, 58000.0],
       [0.0, 0.0, 1.0, 38.77777777777778, 52000.0],
       [1.0, 0.0, 0.0, 48.0, 79000.0],
       [0.0, 1.0, 0.0, 50.0, 83000.0],
       [1.0, 0.0, 0.0, 37.0, 67000.0]], dtype=object)

## Encoding Dependent Variables

In [62]:
le = LabelEncoder()
y = le.fit_transform(y)
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

# Splitting the data into training and testing datasets

In [63]:
train_test_split(X,y,test_size = 0.2)
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.2)
X_train, X_test, y_train, y_test

(array([[0.0, 0.0, 1.0, 38.0, 61000.0],
        [0.0, 1.0, 0.0, 30.0, 54000.0],
        [0.0, 1.0, 0.0, 40.0, 63777.77777777778],
        [1.0, 0.0, 0.0, 35.0, 58000.0],
        [0.0, 0.0, 1.0, 27.0, 48000.0],
        [1.0, 0.0, 0.0, 48.0, 79000.0],
        [1.0, 0.0, 0.0, 44.0, 72000.0],
        [0.0, 1.0, 0.0, 50.0, 83000.0]], dtype=object),
 array([[1.0, 0.0, 0.0, 37.0, 67000.0],
        [0.0, 0.0, 1.0, 38.77777777777778, 52000.0]], dtype=object),
 array([0, 0, 1, 1, 1, 1, 0, 0]),
 array([1, 0]))

# Scaling Features

In [64]:
sc = StandardScaler()
X_train[:,3:] = sc.fit_transform(X_train[:,3:])
X_train

array([[0.0, 0.0, 1.0, -0.13046561461068845, -0.3365660580973627],
       [0.0, 1.0, 0.0, -1.174190531496196, -0.9489461782456332],
       [0.0, 1.0, 0.0, 0.13046561461068845, -0.09355807391154077],
       [1.0, 0.0, 0.0, -0.5218624584427538, -0.5990146810180501],
       [0.0, 0.0, 1.0, -1.5655873753282612, -1.473843424087008],
       [1.0, 0.0, 0.0, 1.174190531496196, 1.2381256794267617],
       [1.0, 0.0, 0.0, 0.6523280730534422, 0.6257455592784911],
       [0.0, 1.0, 0.0, 1.4351217607175728, 1.5880571766543448]],
      dtype=object)

In [65]:
X_test[:,3:] = sc.transform(X_test[:,3:])
X_test

array([[1.0, 0.0, 0.0, -0.2609312292213769, 0.18833118774401206],
       [0.0, 0.0, 1.0, -0.028992358802375107, -1.1239119268594249]],
      dtype=object)

# Exercise